<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ktype" nsURI="http://www.example.org/kindness_metamodel_ktypes"
    nsPrefix="kindness">
  <eClassifiers xsi:type="ecore:EClass" name="KObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ktype" lowerBound="1" eType="#//KType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KHuman" eSuperTypes="#//KPhysical"/>
  <eClassifiers xsi:type="ecore:EClass" name="KDigital" eSuperTypes="#//KType"/>
  <eClassifiers xsi:type="ecore:EClass" name="KPhysical" eSuperTypes="#//KType"/>
  <eClassifiers xsi:type="ecore:EClass" name="KSocial" eSuperTypes="#//KType"/>
</ecore:EPackage>
